user:
  id: admin
  pwd: 12345
  
spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create-drop

    datasource:
        url: jdbc:mysql://localhost:3306/devops
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver